import {
  ProductDetail,
  ProductSummary,
  ReviewIntelligenceReport,
  QueryResponse,
  ComparisonResponse,
  RecommendationResponse,
} from '../types';

export const MOCK_CATEGORIES = [
  {
    id: 'cat_guitars',
    name: 'Guitars & Basses',
    itemCount: 2840,
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80',
    description: 'Electric, acoustic, and bass guitars with verified pickup and tonewood provenance.',
  },
  {
    id: 'cat_mics',
    name: 'Microphones & Vocals',
    itemCount: 1420,
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
    description: 'Dynamic and condenser broadcast mics with noise floor and capsule specs.',
  },
  {
    id: 'cat_interfaces',
    name: 'Audio Interfaces',
    itemCount: 960,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
    description: 'High-headroom preamps, USB-C DACs, and ultra-low-latency monitoring hubs.',
  },
  {
    id: 'cat_keys',
    name: 'Keyboards & Synths',
    itemCount: 1150,
    image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&w=800&q=80',
    description: 'Weighted hammer action digital pianos, analog synthesizers, and MIDI controllers.',
  },
  {
    id: 'cat_drums',
    name: 'Drums & Percussion',
    itemCount: 840,
    image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=800&q=80',
    description: 'Poplar shell acoustic kits, mesh electronic drum heads, and cymbals.',
  },
  {
    id: 'cat_studio',
    name: 'Studio Monitors & Cans',
    itemCount: 1680,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    description: 'Flat-response reference headphones and nearfield acoustic monitors.',
  },
];

export const MOCK_PRODUCTS: ProductDetail[] = [
  {
    id: 'B0002E1O2C',
    title: 'Shure SM7B Cardioid Dynamic Vocal Microphone',
    average_rating: 4.8,
    rating_count: 2840,
    price: 399.0,
    price_currency: 'USD',
    brand_name: 'Shure',
    category_id: 'cat_mics',
    image_url: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_shure', name: 'Shure' },
    category: { id: 'cat_mics', name: 'Microphones', level: 1 },
    main_category: 'Musical Instruments',
    features: [
      'Uniform cardioid polar pattern for maximum rejection of off-axis sound',
      'Flat, wide-range frequency response (50Hz - 20kHz)',
      'Air suspension shock isolation and internal pop filter',
      'Shielding against broadband electromagnetic interference from PC monitors',
      'Requires substantial clean gain (recommended 60dB+ preamp)',
    ],
    description: [
      'The Shure SM7B dynamic microphone has a smooth, flat, wide-range frequency response appropriate for music and speech in all professional audio applications. It features excellent shielding against electromagnetic hum generated by computer monitors, neon lights, and other electrical devices.',
    ],
    details: {
      'Connector Type': 'XLR 3-Pin',
      'Polar Pattern': 'Cardioid',
      'Impedance': '150 Ohms',
      'Item Weight': '1.69 lbs',
      'Dimensions': '7.49 x 3.78 x 5.86 inches',
    },
    raw_price: '$399.00',
  },
  {
    id: 'B0002CZV82',
    title: 'Fender Player Stratocaster Electric Guitar - Maple Fingerboard, Polar White',
    average_rating: 4.7,
    rating_count: 1420,
    price: 849.99,
    price_currency: 'USD',
    brand_name: 'Fender',
    category_id: 'cat_guitars',
    image_url: 'https://images.unsplash.com/photo-1550291652-6ea9114a47b1?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_fender', name: 'Fender' },
    category: { id: 'cat_guitars', name: 'Electric Guitars', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'Alder body with gloss finish',
      'Three Player Series single-coil Stratocaster pickups',
      'Modern C-shaped neck profile with 9.5-inch radius maple fingerboard',
      '2-point tremolo bridge with bent-steel saddles',
      'Dedicated bridge pickup tone control',
    ],
    description: [
      'The inspiring sound of a Stratocaster is one of the foundations of Fender. Featuring this classic sound—bell-like high end, punchy mids and robust low end, combined with crystal-clear articulation—the Player Stratocaster is packed with authentic Fender feel and style.',
    ],
    details: {
      'Body Material': 'Alder',
      'Neck Material': 'Maple',
      'Number of Strings': '6',
      'Scale Length': '25.5 inches',
      'Hand Orientation': 'Right Handed',
    },
    raw_price: '$849.99',
  },
  {
    id: 'B07BS8ND1B',
    title: 'Focusrite Scarlett 2i2 3rd Gen USB Audio Interface',
    average_rating: 4.6,
    rating_count: 3110,
    price: 179.99,
    price_currency: 'USD',
    brand_name: 'Focusrite',
    category_id: 'cat_interfaces',
    image_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_focusrite', name: 'Focusrite' },
    category: { id: 'cat_interfaces', name: 'Audio Interfaces', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'Two upgraded Scarlett mic preamps with switchable Air mode',
      'Two high-headroom instrument inputs for guitar or bass',
      '24-bit/192kHz converters for studio-quality capture',
      'Gain Halos for intuitive, visual signal metering',
      'USB-C bus-powered with zero-latency direct monitoring',
    ],
    description: [
      'Focusrite Scarlett 2i2 gives musicians and creators a simple, compact recording solution with pristine audio clarity. Switch on the Air mode for brighter, more open acoustic vocal and instrument recordings.',
    ],
    details: {
      'Connectivity': 'USB Type-C',
      'Simultaneous I/O': '2 x 2',
      'Preamps': '2 with 48V Phantom Power',
      'Bit Depth / Sample Rate': '24-bit / 192kHz',
    },
    raw_price: '$179.99',
  },
  {
    id: 'B07W4DBR47',
    title: 'Boss Katana 50 MkII 50-watt 1x12 Guitar Combo Amplifier',
    average_rating: 4.8,
    rating_count: 1890,
    price: 269.99,
    price_currency: 'USD',
    brand_name: 'BOSS',
    category_id: 'cat_guitars',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_boss', name: 'BOSS' },
    category: { id: 'cat_guitars', name: 'Guitar Amplifiers', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'Stage-ready 50-watt combo amp with custom 12-inch speaker',
      'Tube Logic design produces class-defying power and punch',
      'Five unique amp characters: Clean, Crunch, Lead, Brown, and Acoustic',
      'Five independent effects sections (Booster, Mod, FX, Delay, and Reverb)',
      'Power Control for cranked-amp tone and response at low volumes',
    ],
    description: [
      'Katana MkII takes the acclaimed Katana guitar amp series to the next level, turbocharging the core platform with more sounds, more effects, and more features. Newly voiced variations are now available for all five amp characters.',
    ],
    details: {
      'Output Power': '50W (switchable to 25W, 0.5W)',
      'Speaker Size': '1 x 12"',
      'Presets': '4 Tone Setting memories',
    },
    raw_price: '$269.99',
  },
  {
    id: 'B016AP0X4O',
    title: 'Yamaha P-125 88-Key Weighted Action Digital Piano',
    average_rating: 4.7,
    rating_count: 980,
    price: 649.99,
    price_currency: 'USD',
    brand_name: 'Yamaha',
    category_id: 'cat_keys',
    image_url: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_yamaha', name: 'Yamaha' },
    category: { id: 'cat_keys', name: 'Digital Pianos', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'GHS (Graded Hammer Standard) weighted 88-key action',
      'Pure CF Sound Engine faithfully reproduces Yamaha CFIIIS Concert Grand',
      '2-way speaker system produces expansive stereo sound',
      'Stereophonic Optimizer delivers realistic acoustic spatial presence in headphones',
      'Compatible with Smart Pianist iOS app',
    ],
    description: [
      'The Yamaha P-125 is a compact digital piano that combines incredible piano performance with a friendly, minimalistic design. Easily portable and extremely accessible, it lets you experience the joy of playing the piano on your terms.',
    ],
    details: {
      'Number of Keys': '88',
      'Key Action': 'Graded Hammer Standard (GHS)',
      'Polyphony': '192 Notes',
      'Voices': '24 Instrument Voices',
    },
    raw_price: '$649.99',
  },
  {
    id: 'B0007L8B7E',
    title: 'Audio-Technica ATH-M50x Professional Studio Monitor Headphones',
    average_rating: 4.7,
    rating_count: 5430,
    price: 149.0,
    price_currency: 'USD',
    brand_name: 'Audio-Technica',
    category_id: 'cat_studio',
    image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_audio_technica', name: 'Audio-Technica' },
    category: { id: 'cat_studio', name: 'Headphones', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'Critically acclaimed sonic performance praised by top audio engineers',
      'Proprietary 45 mm large-aperture drivers with rare earth magnets',
      'Exceptional clarity throughout an extended frequency range (15Hz - 28kHz)',
      'Circumaural design contours around ears for excellent passive noise isolation',
      '90-degree swiveling earcups for easy, one-ear monitoring',
    ],
    description: [
      'As the most critically acclaimed model in the M-Series line, the ATH-M50x is praised by top audio engineers and pro audio reviewers year after year. From the large-aperture drivers to the sound isolating earcups and robust construction.',
    ],
    details: {
      'Driver Size': '45 mm',
      'Sensitivity': '99 dB',
      'Impedance': '38 Ohms',
      'Cable Types': '3 detachable cables included',
    },
    raw_price: '$149.00',
  },
  {
    id: 'B00K5OXW3G',
    title: 'Pearl Export EXX 5-Piece Complete Drum Set with Hardware',
    average_rating: 4.5,
    rating_count: 410,
    price: 799.0,
    price_currency: 'USD',
    brand_name: 'Pearl',
    category_id: 'cat_drums',
    image_url: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_pearl', name: 'Pearl' },
    category: { id: 'cat_drums', name: 'Acoustic Drum Sets', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      '6-ply 7.5mm blended Poplar and Asian Mahogany shells',
      'Opti-Loc tom suspension mounting system',
      '830 Series double-braced hardware package included',
      'Demonator P-930 single bass drum pedal included',
      'Remo coated snare and clear tom drumheads',
    ],
    description: [
      'The kit that spawned a thousand drumming legends. Pearl Export series drums offer reference-inspired shell construction with Superior Shell Technology (SST) for resonant acoustic projection.',
    ],
    details: {
      'Shell Material': 'Poplar / Asian Mahogany',
      'Configuration': '22" Kick, 10" & 12" Toms, 16" Floor Tom, 14" Snare',
      'Hardware': 'Chrome double-braced',
    },
    raw_price: '$799.00',
  },
  {
    id: 'B0010S74LU',
    title: 'Korg microKORG 37-Key Analog Modeling Synthesizer with Vocoder',
    average_rating: 4.6,
    rating_count: 670,
    price: 429.99,
    price_currency: 'USD',
    brand_name: 'Korg',
    category_id: 'cat_keys',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    brand: { id: 'brand_korg', name: 'Korg' },
    category: { id: 'cat_keys', name: 'Synthesizers', level: 2 },
    main_category: 'Musical Instruments',
    features: [
      'Multi-engine analog modeling synthesis system (DSP-based)',
      'Integrated 8-band vocoder with goose-neck microphone included',
      '128 built-in presets organized by musical genres',
      'Programmable arpeggiator with 6 pattern variations',
      'Operates on AC adapter or 6 AA alkaline batteries for portable jamming',
    ],
    description: [
      'The microKORG is a compact, battery-powered synthesizer/vocoder that combines analog modeling sound synthesis with retro styling and performance ergonomics that modern sound designers revere.',
    ],
    details: {
      'Keys': '37 Velocity-sensing mini keys',
      'Synthesis': 'Analog Modeling DSP',
      'Polyphony': '4 voices',
      'Effects': 'Modulation, Delay, 2-band EQ',
    },
    raw_price: '$429.99',
  },
];

export const MOCK_REVIEW_INTELLIGENCE: Record<string, ReviewIntelligenceReport> = {
  B0002E1O2C: {
    product_id: 'B0002E1O2C',
    distribution: {
      total_reviews: 2840,
      average_rating: 4.8,
      verified_count: 2510,
      unverified_count: 330,
      star_counts: { 5: 2360, 4: 310, 3: 90, 2: 45, 1: 35 },
    },
    aspects: [
      {
        aspect: 'Vocal Warmth & Presence',
        sentiment: 'positive',
        mention_count: 820,
        sample_quotes: [
          'Gives speech and vocals a radio-broadcast thickness you cannot replicate with plugins.',
          'The roll-off and mid-range boost switches allow tuning for boomy or harsh voices.',
        ],
      },
      {
        aspect: 'Off-Axis Rejection',
        sentiment: 'positive',
        mention_count: 640,
        sample_quotes: [
          'Literally silences my noisy mechanical keyboard and computer fans in an untreated bedroom.',
          'Cardioid pattern is razor sharp.',
        ],
      },
      {
        aspect: 'Gain Requirements (Preamp Need)',
        sentiment: 'neutral',
        mention_count: 490,
        sample_quotes: [
          'Be prepared: you WILL need a Cloudlifter or an interface with at least 60dB clean gain.',
          'Directly into entry-level interfaces you get noticeable noise floor unless boosted.',
        ],
      },
      {
        aspect: 'Build Quality & Durability',
        sentiment: 'positive',
        mention_count: 380,
        sample_quotes: ['Built like an absolute tank. Heavy cast aluminum housing.'],
      },
    ],
    top_positive_snippets: [
      'Gives speech and vocals a radio-broadcast thickness you cannot replicate with plugins.',
      'Literally silences my noisy mechanical keyboard and computer fans in an untreated bedroom.',
      'Built like an absolute tank. Heavy cast aluminum housing.',
    ],
    top_negative_snippets: [
      'Be prepared: you WILL need a Cloudlifter or an interface with at least 60dB clean gain.',
      'Heavy weight requires a sturdy boom arm; cheap scissor arms will droop.',
    ],
    summary:
      'The Shure SM7B is the gold standard vocal microphone for broadcasting and home studio tracking. Reviewers overwhelmingly praise its broadcast warmth and exceptional noise rejection, while noting its heavy gain appetite (60dB+ required).',
  },
  B0002CZV82: {
    product_id: 'B0002CZV82',
    distribution: {
      total_reviews: 1420,
      average_rating: 4.7,
      verified_count: 1280,
      unverified_count: 140,
      star_counts: { 5: 1110, 4: 210, 3: 55, 2: 25, 1: 20 },
    },
    aspects: [
      {
        aspect: 'Strat Bell Tone Articulation',
        sentiment: 'positive',
        mention_count: 460,
        sample_quotes: ['Position 2 and 4 have that quintessential glassy Hendrix quack.'],
      },
      {
        aspect: 'Neck Playability & Finish',
        sentiment: 'positive',
        mention_count: 390,
        sample_quotes: ['Satin finish on the back of the neck feels fast and never gets sticky.'],
      },
      {
        aspect: 'Factory Setup',
        sentiment: 'neutral',
        mention_count: 180,
        sample_quotes: ['Needed a slight truss rod adjustment and intonation tweak out of the box.'],
      },
    ],
    top_positive_snippets: [
      'Position 2 and 4 have that quintessential glassy Hendrix quack.',
      'Satin finish on the back of the neck feels fast and never gets sticky.',
    ],
    top_negative_snippets: [
      'Needed a slight truss rod adjustment and intonation tweak out of the box.',
    ],
    summary:
      'The Fender Player Stratocaster delivers genuine Mexican Fender craftsmanship with classic single-coil chime and ergonomic modern C neck playability.',
  },
};

export const MOCK_QUERY_RESPONSE: QueryResponse = {
  query: 'Best microphone for untreated home studio vocals under $450',
  intent: 'product_search',
  strategy_used: 'HYBRID',
  answer:
    'For untreated home studios under $450, the **Shure SM7B** [1] is the most recommended choice. Its dynamic transducer design and tight cardioid polar pattern naturally reject ambient room reflections, PC fan noise, and mechanical vibrations [2]. Unlike sensitive condenser microphones that capture flutter echo in untreated spaces, the SM7B exhibits high sound pressure handling and exceptional electromagnetic shielding [3]. Note that it requires 60dB+ of clean gain, making a dedicated preamp or high-gain interface like the Focusrite Scarlett 2i2 [4] essential.',
  products: [MOCK_PRODUCTS[0], MOCK_PRODUCTS[2]],
  evidence: [
    {
      id: 'ev_01',
      evidence_type: 'OBSERVED_GRAPH_FACT',
      source: 'Product.price',
      product_id: 'B0002E1O2C',
      value: 399.0,
      description: 'Grounded Neo4j price is $399.00 USD, satisfying the < $450 ceiling constraint.',
      confidence: 1.0,
    },
    {
      id: 'ev_02',
      evidence_type: 'REVIEW_EVIDENCE',
      source: 'Review.text',
      product_id: 'B0002E1O2C',
      value: 'Cardioid pattern rejects mechanical keyboard and fan noise in untreated rooms',
      description: 'Extracted from 640 verified purchaser reviews mentioning off-axis noise rejection.',
      confidence: 0.94,
    },
    {
      id: 'ev_03',
      evidence_type: 'OBSERVED_GRAPH_FACT',
      source: 'Category.name',
      product_id: 'B0002E1O2C',
      value: 'Microphones',
      description: 'Product belongs to canonical Musical Instruments > Microphones taxonomy.',
      confidence: 1.0,
    },
    {
      id: 'ev_04',
      evidence_type: 'RECOMMENDATION_INFERENCE',
      source: 'GraphTraversal[:ALSO_PURCHASED]',
      product_id: 'B07BS8ND1B',
      value: 'Focusrite Scarlett 2i2 co-purchased by 34% of SM7B owners',
      description: 'High graph co-purchase weight connecting SM7B to Scarlett 2i2 preamp hub.',
      confidence: 0.88,
    },
  ],
  cypher_executed:
    'MATCH (p:Product)-[:BELONGS_TO]->(c:Category {name: "Microphones"})\nWHERE p.price <= 450.0 AND p.average_rating >= 4.5\nRETURN p ORDER BY p.average_rating DESC LIMIT 5;',
  explanation:
    'Retrieved via Hybrid Graph-RAG: 1) Cypher filtered canonical Microphones with price <= $450 and rating >= 4.5; 2) Vector similarity ranked acoustic suitability for "untreated home studio"; 3) Review intelligence aggregated aspect sentiments for background rejection.',
  limitations: [
    'Requires an audio interface or in-line booster with at least 60dB clean gain (not included in box).',
    'Heavier weight (1.69 lbs) requires a sturdy desk boom arm.',
  ],
  latency_breakdown_ms: {
    intent_classification_ms: 18.4,
    cypher_retrieval_ms: 24.1,
    vector_ann_ms: 31.8,
    review_aspect_fusion_ms: 16.2,
    llm_synthesis_ms: 142.5,
    total_ms: 233.0,
  },
};

export const MOCK_RECOMMENDATION_RESPONSE: RecommendationResponse = {
  query: 'Studio tracking chain for vocalists',
  target_product_id: 'B0002E1O2C',
  total_found: 3,
  weights_applied: {
    category_match: 0.2,
    rating_quality: 0.25,
    price_fit: 0.15,
    brand_authority: 0.1,
    semantic_similarity: 0.15,
    purchaser_overlap: 0.15,
  },
  recommendations: [
    {
      product: MOCK_PRODUCTS[2], // Focusrite Scarlett 2i2
      composite_score: 0.94,
      explanation: {
        product_id: 'B07BS8ND1B',
        product_title: 'Focusrite Scarlett 2i2 3rd Gen USB Audio Interface',
        summary_reason:
          '34% of verified SM7B purchasers simultaneously purchased the Scarlett 2i2 to drive XLR signal conversion.',
        factors: [
          {
            factor_name: 'purchaser_overlap',
            weight: 0.15,
            score: 0.96,
            weighted_score: 0.144,
            evidence_type: 'OBSERVED_GRAPH_FACT',
            explanation: 'Multi-hop graph traversal found 412 shared verified reviewer nodes.',
          },
          {
            factor_name: 'rating_quality',
            weight: 0.25,
            score: 0.92,
            weighted_score: 0.23,
            evidence_type: 'OBSERVED_GRAPH_FACT',
            explanation: 'Bayesian rating score 4.6 based on 3,110 verified reviews.',
          },
          {
            factor_name: 'price_fit',
            weight: 0.15,
            score: 0.95,
            weighted_score: 0.1425,
            evidence_type: 'OBSERVED_GRAPH_FACT',
            explanation: '$179.99 is well within the typical 50% ratio for vocal front-end gear.',
          },
          {
            factor_name: 'semantic_similarity',
            weight: 0.15,
            score: 0.91,
            weighted_score: 0.1365,
            evidence_type: 'VECTOR_SIMILARITY',
            explanation: 'Embeddings closely align on "studio preamp", "low noise floor", and "USB recording".',
          },
        ],
        graph_paths: [
          [
            {
              start_node: 'Shure SM7B (B0002E1O2C)',
              start_label: 'Product',
              relationship: 'CO_PURCHASED_WITH',
              end_node: 'Focusrite Scarlett 2i2 (B07BS8ND1B)',
              end_label: 'Product',
            },
          ],
        ],
        review_evidence_quotes: [
          'Paired this directly with my SM7B and Cloudlifter, sounds immaculate.',
        ],
        observed_facts: ['Price: $179.99', 'Preamps: 2 XLR inputs with 48V phantom power'],
        inferred_aspects: ['High compatibility for home podcasting and vocal tracking chains.'],
        limitations: ['May need an in-line booster for very quiet spoken word.'],
      },
    },
    {
      product: MOCK_PRODUCTS[5], // ATH-M50x
      composite_score: 0.89,
      explanation: {
        product_id: 'B0007L8B7E',
        product_title: 'Audio-Technica ATH-M50x Studio Headphones',
        summary_reason:
          'Zero acoustic bleed closed-back design essential for real-time SM7B vocal tracking.',
        factors: [
          {
            factor_name: 'category_match',
            weight: 0.2,
            score: 0.94,
            weighted_score: 0.188,
            evidence_type: 'OBSERVED_GRAPH_FACT',
            explanation: 'Studio Recording category complement.',
          },
          {
            factor_name: 'rating_quality',
            weight: 0.25,
            score: 0.95,
            weighted_score: 0.2375,
            evidence_type: 'OBSERVED_GRAPH_FACT',
            explanation: 'Bayesian rating 4.7 with over 5,400 reviews.',
          },
        ],
        graph_paths: [],
        review_evidence_quotes: ['Essential closed-back cans to prevent backing track bleed into vocal mic.'],
        observed_facts: ['Price: $149.00', 'Driver: 45mm', 'Design: Closed-back circumaural'],
        inferred_aspects: ['Ideal monitoring partner during live takes.'],
        limitations: [],
      },
    },
  ],
  evidence_items: [],
};

export const MOCK_COMPARISON_RESPONSE: ComparisonResponse = {
  products: [
    {
      product: MOCK_PRODUCTS[0], // SM7B
      review_intelligence: MOCK_REVIEW_INTELLIGENCE['B0002E1O2C'],
      strengths: [
        'Exceptional ambient noise and off-axis rejection',
        'Iconic warm broadcast proximity effect',
        'Bulletproof metal construction and internal air suspension',
      ],
      tradeoffs: [
        'Requires 60dB+ clean gain / secondary booster',
        'Higher initial investment ($399.00)',
      ],
    },
    {
      product: {
        ...MOCK_PRODUCTS[0],
        id: 'B0002GZKWU',
        title: 'Rode NT1 5th Gen Large-Diaphragm Cardioid Condenser',
        price: 249.0,
        average_rating: 4.6,
        rating_count: 1120,
        brand_name: 'Røde',
        features: [
          'Ultra-low self-noise (4dBA)',
          'Dual Connect output (XLR and USB-C with 32-bit float)',
          'High SPL handling (142dB)',
        ],
        details: {
          'Transducer': 'Condenser',
          'Self Noise': '4 dBA',
          'Output': 'XLR & USB-C',
        },
      },
      review_intelligence: null,
      strengths: [
        'World record 4dBA ultra-low self-noise floor',
        'Built-in 32-bit float USB recording directly into DAW',
        'Crisp, airy high frequencies on acoustic instruments',
      ],
      tradeoffs: [
        'Captures significant room reverberation if room is untreated',
        'Fragile gold-sputtered capsule sensitive to drops and moisture',
      ],
    },
  ],
  matrix: {
    'Transducer Type': {
      B0002E1O2C: 'Dynamic (Moving Coil)',
      B0002GZKWU: 'Condenser (Gold-sputtered)',
    },
    'Price (USD)': {
      B0002E1O2C: '$399.00',
      B0002GZKWU: '$249.00',
    },
    'Self-Noise Floor': {
      B0002E1O2C: 'Passive (Requires high-gain preamp)',
      B0002GZKWU: '4 dBA (Ultra-quiet internal FET)',
    },
    'Untreated Room Rejection': {
      B0002E1O2C: 'Superior (Rejects HVAC and key clicks)',
      B0002GZKWU: 'Moderate (Picks up room flutter echo)',
    },
    'Ideal Application': {
      B0002E1O2C: 'Vocal broadcast, rock screaming, untreated rooms',
      B0002GZKWU: 'Acoustic guitar, subtle voiceover, treated booths',
    },
  },
  llm_synthesis:
    '**Comparison Summary**: For untreated bedroom studios or streamers, the **Shure SM7B** wins decisively due to its dynamic rejection of background noise and warm proximity effect. However, if you record in a quiet treated acoustic space or need direct USB-C 32-bit float connectivity without buying an interface, the **Røde NT1 5th Gen** provides greater detail at a $150 lower entry point.',
  evidence_items: [],
  limitations: [
    'Røde NT1 5th Gen includes shockmount and pop shield; SM7B includes only integrated windscreen.',
  ],
};
